package com.utilityinternational.entity.enums;

/**
 * The lifecycle state of a {@code MonthlyBill} as it moves through the
 * self-service workflow described in the use case specifications:
 * View Bill, Dispute Bill, Resolve Disputed Bill and Pay Bill.
 *
 * <p>Part of the dedicated <strong>enum package</strong>. Persisted with
 * {@code @Enumerated(EnumType.STRING)} so the stored value is the readable
 * constant name (e.g. {@code "DISPUTED"}).</p>
 */
public enum BillStatus {

    /** Bill generated by the billing system, awaiting customer review. */
    OUTSTANDING("Outstanding"),

    /** Customer has rejected the bill and supplied supporting context. */
    DISPUTED("Disputed"),

    /** A disputed bill the call centre agent judged valid; returned for payment. */
    REJECTED_DISPUTE("Dispute Rejected"),

    /** A disputed bill the call centre agent accepted; adjusted/closed. */
    RESOLVED("Resolved"),

    /** Customer has paid the bill in full. */
    PAID("Paid");

    private final String label;

    BillStatus(String label) {
        this.label = label;
    }

    public String getLabel() {
        return label;
    }
}
